const express = require("express");
const app = express();

// Establishing URL Parser
app.use(express.urlencoded({ extended: false }));

// MongoDB Connection Setup

const mongoose = require("mongoose");
mongoose.set("strictQuery", false);

const connectionString = "mongodb+srv://Admin-Mitadru:DB1234@clustermg.e4fjgoy.mongodb.net/blogDB?retryWrites=true&w=majority&appName=ClusterMG";

async function main(){
    await mongoose.connect(connectionString);
}

main().catch((error) => console.log(error));

// Authentication Utility

const passport = require("passport");
require("./passport/config");

const session = require("express-session"); // Dependency used in the background by passport.js

app.use(session({ secret: "randomSecret", resave: false, saveUninitialized: true }));
app.use(passport.session());

// Routing

const cors = require("cors");   
app.use(cors({ credentials: true })); // {credentials: true} => because we will send the request with the session generated by passport

const indexRouter = require("./routes/index");
const dashboardRouter = require("./routes/dashboard");

app.use("/index", indexRouter);
app.use("/dashboard", dashboardRouter);

app.get("/", (req, res) => {res.status(200).json("Welcome!")});

module.exports = app;